# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../salt", "/srv/salt"
  config.vm.synced_folder "../salt-pillars", "/srv/pillar"
 
  config.vm.provision :shell, path: "salt/saltprovision.sh", privileged: false

end
