Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "provision", "/vagrant"

 config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
   end
  
  config.vm.provision "shell" do |s|
    s.path = "provision/setup.sh"
  end

end